# Generated by Django 4.1b1 on 2022-07-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_unit_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="birth_date",
        ),
    ]
