# Generated by Django 4.1rc1 on 2022-07-25 09:11

import cloudinary.models
from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_customer_email_alter_customer_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
