# Generated by Django 4.1rc1 on 2022-08-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
